# Generated by Django 5.2.7 on 2025-11-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_season', '-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('popular', 'Популярное'), ('best_seller', 'Бестселлер')], help_text='Популярное или Бестселлер (может быть пустым)', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
