# Generated by Django 5.2.7 on 2026-03-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото продукта', 'verbose_name_plural': 'Фотки продукта'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Размер продукта', 'verbose_name_plural': 'Размеры продукта'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='sizetype',
            options={'verbose_name': 'Название размера', 'verbose_name_plural': 'Название размеров'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set(),
        ),
    ]
