# Generated by Django 5.2.7 on 2026-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(choices=[('china', 'Китай'), ('usa', 'США'), ('europe', 'Европа'), ('russia', 'Россия')], default='china', max_length=20),
        ),
    ]
