# Generated by Django 5.2.7 on 2026-05-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_outfit_outfititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outfit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(choices=[('china', 'Китай'), ('usa', 'США'), ('europe', 'Европа'), ('russia', 'Россия'), ('uzbekistan', 'Узбекистан')], default='china', max_length=20),
        ),
    ]
