# Generated by Django 5.2.7 on 2026-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_outfit_discount_outfit_price_alter_product_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unisex', 'Унисекс')], default='unisex', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unisex', 'Унисекс')], default='unisex', max_length=10, verbose_name='Пол'),
        ),
    ]
