# Generated by Django 5.2.7 on 2026-06-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_outfit_gender_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='cargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Карго'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='delivery_time',
            field=models.CharField(default='10-15 дней', max_length=100, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наценка'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Вес в кг', max_digits=6, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='product',
            name='cargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Карго'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(default='10-15 дней', max_length=100, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='product',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наценка'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Вес в кг', max_digits=6, verbose_name='Вес'),
        ),
    ]
