# Generated by Django 5.2.7 on 2026-06-08 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_outfit_cargo_outfit_delivery_time_outfit_markup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['id'], 'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('size_type', 'name')},
        ),
        migrations.CreateModel(
            name='ProductSizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Таблица размеров', max_length=255, verbose_name='Заголовок')),
                ('note', models.TextField(blank=True, help_text='Например: Возможна погрешность 1-3 см', null=True, verbose_name='Примечание')),
                ('columns', models.JSONField(default=list, help_text='Например: ["Размер", "Рост", "Вес", "Грудь"]', verbose_name='Колонки')),
                ('rows', models.JSONField(default=list, help_text='Например: [["S", "165-170", "50-55", "100"], ["M", "170-175", "55-60", "104"]]', verbose_name='Строки')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size_chart', to='product.product')),
            ],
            options={
                'verbose_name': 'Таблица размеров',
                'verbose_name_plural': 'Таблицы размеров',
            },
        ),
    ]
