# Generated by Django 5.2.7 on 2026-06-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_size_options_alter_productsize_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название шаблона')),
                ('title', models.CharField(default='Таблица размеров', max_length=255, verbose_name='Заголовок')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('columns', models.JSONField(default=list, verbose_name='Колонки')),
                ('rows', models.JSONField(default=list, verbose_name='Строки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Таблица размеров',
                'verbose_name_plural': 'Таблицы размеров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.sizechart', verbose_name='Таблица размеров'),
        ),
        migrations.DeleteModel(
            name='ProductSizeChart',
        ),
    ]
