# Generated by Django 5.2.7 on 2026-06-14 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_sizechart_product_size_chart_delete_productsizechart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_view', 'Просмотр товара'), ('search', 'Поиск'), ('favorite_add', 'Добавил в избранное'), ('favorite_remove', 'Удалил из избранного'), ('cart_add', 'Добавил в корзину'), ('cart_remove', 'Удалил из корзины'), ('telegram_order_click', 'Клик Telegram-заказ')], max_length=50)),
                ('product_slug', models.SlugField(blank=True, max_length=265, null=True)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие пользователя',
                'verbose_name_plural': 'События пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
