# Generated by Django 5.2.7 on 2026-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='delivery_time',
            field=models.CharField(default='1', max_length=100, verbose_name='Время доставки'),
        ),
    ]
