# Generated by Django 5.2.7 on 2026-06-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_product_link_alter_outfit_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа вариантов товара',
                'verbose_name_plural': 'Группы вариантов товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Например: #000000', max_length=20, null=True, verbose_name='HEX цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productvariantgroup', verbose_name='Группа вариантов'),
        ),
    ]
