# Generated by Django 5.2.7 on 2026-06-22 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productvariantgroup_product_color_hex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantgroup',
            options={'ordering': ['-id'], 'verbose_name': 'Цветовой вариант товара', 'verbose_name_plural': 'Цветовые варианты товаров'},
        ),
        migrations.AlterModelOptions(
            name='sizechart',
            options={'ordering': ['-id'], 'verbose_name': 'Таблица размеров', 'verbose_name_plural': 'Таблицы размеров'},
        ),
        migrations.AddField(
            model_name='outfit',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Например: #000000', max_length=20, null=True, verbose_name='HEX код цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productvariantgroup', verbose_name='Группа цветовых вариантов'),
        ),
        migrations.AlterField(
            model_name='productvariantgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название цветовой группы'),
        ),
    ]
