# Generated by Django 5.2.7 on 2026-07-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_brand_is_active_brand_sort_order_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outfits', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.outfit', verbose_name='Образ')),
            ],
            options={
                'verbose_name': 'Фото образа',
                'verbose_name_plural': 'Фотографии образа',
                'ordering': ['order', 'id'],
            },
        ),
    ]
