# Generated by Django 5.2.7 on 2026-07-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_migrate_outfit_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfitimage',
            name='image',
        ),
    ]
