# Generated by Django 5.2.7 on 2026-07-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_outfitimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits', verbose_name='Фото'),
        ),
    ]
