# Generated by Django 5.2.7 on 2026-07-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_outfitimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitimage',
            name='image',
            field=models.ImageField(upload_to='outfits', verbose_name='Фото'),
        ),
    ]
