# Generated by Django 5.2.7 on 2026-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_pendinguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
        migrations.DeleteModel(
            name='PhoneConfirmation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
