# Generated by Django 5.2.7 on 2026-02-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_pendinguser_delete_phoneconfirmation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
