# Generated by Django 5.2.7 on 2025-11-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_brand_created_at_alter_brand_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum')], max_length=20)),
                ('status', models.CharField(choices=[('waiting_payment', 'Ожидание оплаты'), ('waiting_confirmation', 'Ожидание подтверждения'), ('delivering', 'Доставляется'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='waiting_confirmation', max_length=30)),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('products_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_with_discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
    ]
