# Generated by Django 5.2.7 on 2026-06-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_fee_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_fee_percent',
        ),
    ]
